lib/Plack/Handler/FCGI.pm

Motivation:
To be able to easily debug a FastCGI Plack application from Eclipse (EPIC) I want it to make it run without spawning worker processes, but run within a single process, as EPIC does not support a debug session to a forked child.
Modifications:
Use //= instead of ||= in Handler::FCGI to allow passing "0" child processes. This makes FCGI::ProcManager run within a single process. See http://search.cpan.org/~gbjk/FCGI-ProcManager-0.19/ProcManager.pm#pm_manage
Result:
Debugging is possible.

Allow Handler::FCGI to run non-forked

---

lib/Plack/Util.pm

`header_exists` and scalar-context `header_get` can short-circuit, and `header_set` and `header_remove` can do their work in one-shot, list-wise operations instead of looping and pushing and copying. And of course it’s always faster to do the work in native loops instead of lots of short function calls plus copying data to globals.
The readability of the code did not even suffer that much, to my mind; `header_set` seems maybe slightly more readable even, and `header_exist` is just as readable as before. The other two have suffered, but not terribly.

Faster header utils

---

cpanfile
lib/Plack/Request.pm
lib/Plack/Response.pm

Can someone profile/benchmark these?
cc @tokuhirom @kazeburo @avar

use HTTP::Headers::Fast

---

lib/Plack/Request.pm
t/Plack-Request/params.t

Plack::Request has a bug (apparently shared with URI::_query) in how it parses empty pairs in the query string. It produces an empty-string key with an empty-key value, rather than ignoring them.
This patch fixes the problem.

Fix parsing of empty query string pairs

---

lib/Plack/Request.pm
t/Plack-Request/params.t

This changes the test to include empty pairs both at the start and in the middle of the string.
Also it avoids the check for empty pairs in every iteration of the `map` by splitting not just on single separators, but on sequences of any number of separators – then the split doesn’t produce empty pairs in the first place. The remaining exception is that it can still do so at the start of the string, so the code first throws away any sequence of leading separators.

Fix parsing of empty query string pairs better

---

lib/Plack/MIME.pm

Probably best to include .webm by default since its a standard and is being used more and more when serving video.

Add .webm to Plack::MIME as 'video/webm'

---

lib/Plack/Middleware/Lint.pm
t/Plack-Middleware/lint_env.t

Plack::Middleware::Lint is handler-agnostic lint; it should accept `SERVER_PROTOCOL`=`HTTP/2` as well.
My case was that when using `Plack::Handler::FCGI` behind [H2O](https://github.com/h2o/h2o), Lint was complaining about `SERVER_PROTOCOL` being set to `HTTP/2`.

[lint] do not forbid SERVER_PROTOCOL=HTTP/2

---

lib/Plack/MIME.pm

Added a MIME type for the Android APK format.
Chrome and the old Android Browser handle APKs fine without a MIME type but Firefox for Android requires that the MIME Type is correct in order to prompt the user to install an app (otherwise it just shows binary data in the browser).
This addition allows (among other things) APKs to be served to Firefox on Android by Plack::Middleware::Static without having to manually add a type.

Added MIME type for Android APK

---

script/plackup

To avoid issues with preloaded modules not affecting the restart
fork while triggering it, the modules need to be loaded with the
app code using -e 'use MyModule;'

Documentation update: combination of -M and -r/-R is problematic.

---

lib/Plack/Runner.pm

In the "directly called" case (i.e. caller is false) we're not running in a sub or a frame from where we can return, so it's a bit weird to put return there.

Shouldn't "return outside a subroutine"

---

lib/Plack/Handler/FCGI.pm

FCGI::ProcManager supports running in single-process mode when
n_processes is zero. It is useful (for harakiri support) to run
with proc manager in single-process mode.
This refactors _create_proc_manager method to create the manager
object. It uses different default manager class and number processes between
listen mode and single process mode. It keeps the old behavior for
single-process mode without manager. It would be possible to create proc manager by default or always.

Support setting "manager" for Plack::Handler::FCGI in single-process mode

---

cpanfile
lib/Plack/Response.pm

`HTTP::Headers::Fast->flatten` was introduced in https://github.com/tokuhirom/HTTP-Headers-Fast/pull/8. `flatten` is shortcut method for building PSGI compatible header array. This PR uses that.
benchmark. Would be 10% faster.
master
```
% perl bench.pl
Benchmark: running bench_hello for at least 3 CPU seconds...
bench_hello:  4 wallclock secs ( 3.22 usr +  0.00 sys =  3.22 CPU) @ 60104.35/s (n=193536)
Rate bench_hello
bench_hello 60104/s          --
```
This PR
```
% perl -Ilib bench.pl
Benchmark: running bench_hello for at least 3 CPU seconds...
bench_hello:  4 wallclock secs ( 3.30 usr +  0.01 sys =  3.31 CPU) @ 66011.48/s (n=218498)
Rate bench_hello
bench_hello 66011/s          --
```
benchmark script
```
use HTTP::Request::Common;
use HTTP::Message::PSGI;
use Plack::Response;
use …
```

use HTTP::Headers::Fast->flatten introduced 0.20

---

cpanfile
lib/Plack/Request.pm
t/Plack-Request/params.t

related to #537 and #434
This PR replace HTTP::Body with HTTP::Entity::Parser and WWW::Form::UrlEncoded(::XS). HTTP::Entity::Parser was created based on tokuhirom's code of #434.
And also this PR remove `Hash::MultiValue->flatten` in `parameters` for reducing cost.
Here is small benchmark this pr and master.
use HTTP::Entity::Parser and WWW::Form::UrlEncoded::XS
```
% perl -Ilib entity_parser_bench.pl
Benchmark: running get, noparam, post for at least 3 CPU seconds...
get:  3 wallclock secs ( 3.11 usr +  0.00 sys =  3.11 CPU) @ 6381.03/s (n=19845)
noparam:  3 wallclock secs ( 3.09 usr +  0.00 sys =  3.09 CPU) @ 7336.57/s (n=22670)
post:  3 wallclock secs ( 3.30 usr +  0.00 sys =  3.30 CPU) @ 5225.15/s (n=17243)
Rate    post     get noparam
post    5225/s      --    -18%    -29%
get …
```

replace HTTP::Body with HTTP::Entity::Parser and optimize query_parameters

---

t/Plack-Middleware/log4perl-category.t

This fixes #543, in which `t/Plack-Middleware/log4perl.t` and `t/Plack-Middleware/log4perl-category.t` may attempt to access the same log file while running in parallel via the `-j` flag.

Allow log4perl.t and log4perl-category.t to run in parallel

---

lib/Plack/Test.pm

I noticed a spacing issue with the docs on Plack::Test, figured it was a simple fix to just tidy them up so that if some one was to copy/paste this code it would pass as intended.

white space issue causes failing test if run

---

cpanfile
lib/Plack/Middleware/AccessLog/Timed.pm
t/Plack-Middleware/access_log_timed.t

ref: #549 https://github.com/kazeburo/Apache-LogFormat-Compiler/pull/12
As described at #549, it's necessary to fix both `Plack` and `Apache::LogFormat::Compiler`.
The bug in `Apache::LogFormat::Compiler` is fixed at https://github.com/kazeburo/Apache-LogFormat-Compiler/pull/12 and released as 0.34.

Make Plack::Middleware::AccessLog::Timed to record %D and %T fields properly

---

Changes
cpanfile
lib/HTTP/Server/PSGI.pm
lib/Plack/Test/Server.pm
t/HTTP-Server-PSGI/harakiri.t
t/HTTP-Server-PSGI/listen.t
t/HTTP-Server-PSGI/post.t
t/Plack-Loader/restarter.t

Adds a `listen_sock` option to HTTP::Server::PSGI and uses this in combination with the new `listen` option to `Test::TCP::test_tcp` (see https://github.com/tokuhirom/Test-TCP/pull/48) to avoid race conditions in the tests.

 Avoid race conditions in tests

---

lib/Plack/Request.pm

just a small doc patch: it's $request->header('Cookie'), not $request->header('Cookies')

doc fix: the http header is called Cookie (singular)

---

cpanfile
lib/Plack/Request.pm
t/Plack-Request/cookie.t

related https://github.com/plack/Plack/pull/564
Use Cookie::Baker to parse cookies. 
Cookie::Baker >= 0.07 allows quoted cookie values, as per RFC 6265

Use Cookie::Baker to parse cookie

---

t/Plack-Request/cookie.t

Related #570 
This PR removes tests that  expects cookie to be delimited by comma.
These tests were added in https://github.com/plack/Plack/pull/149

#570 CVE-2016-7401. Remove tests that expects cookie to be delimited by comma

---

lib/Plack/Request.pm

When a new HTTP entity parser is created, a hardcoded list of parsers for different MIME types is registered. With this patch, the list of MIME types and relative parsers becomes configurable, by means of %Plack::Request::MIME_TYPES. This way, it is easy to add new parsers for additional MIME types.

Make list of HTTP entity parsers configurable

---

lib/Plack/Handler/FCGI.pm

Ref: https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#FcgidPassHeader
I needed this to make it work for me :-)

Fix typo on mod_fcgid directive

---

lib/Plack/Request.pm

HTTP::Headers::Fast tries to preserve the original case in initializer, but in PSGI they're all in upper-case from the environment. This makes a weird result when you try to print headers as a string or use the scan() method, where all incoming keys are all uppercase.
Because HTTP header field names are case insensitive, this should not really matter, but rather than trying to preserve the all-upper case that is coming from PSGI env, just pass it in lowercase, so that the default casing would just work.

Lowercase headers before passing to HTTP::Headers::Fast

---

Changes
cpanfile
lib/HTTP/Server/PSGI.pm
lib/Plack/Test/Server.pm
t/HTTP-Server-PSGI/harakiri.t
t/HTTP-Server-PSGI/listen.t
t/HTTP-Server-PSGI/post.t
t/Plack-Loader/restarter.t

This is a reworking of the reverted #550, which broke some downstream dists. This time the `Plack::Test::Server` part is opt-in, so nothing should break.
Tested with Gazelle (which broke last time) and Starman.

Listen socket take two

---

lib/Plack/App/WrapCGI.pm
t/Plack-Middleware/wrapcgi_exec.t

If `$SIG{CHLD}` is set to `'IGNORE'`, or to a "reaper" coderef, `WrapCGI` (in "execute" mode) stalls in a tight loop when the CGI exits, because `waitpid` returns -1 instead of the positive pid it would usually return.
This patch fixes that (and tests that it works)

protect WrapCGI against SIGCHLD handlers

---

t/Plack-Middleware/directory.t

Fix #591 
As described in #591, `share/#foo` is problematic on StrawberryPerl 5.26.
On the other hand, it is only used in a Plack's own test  t/Plack-Middleware/directory.t.
Thus remove it, and create it only when it is necessary.

Remove share/#foo

---

Changes
lib/Plack/Middleware/XSendfile.pm
t/Plack-Middleware/xsendfile.t

Also add POD documenting the configuration options.

Set Content-Length to 0 in XSendfile middleware #602

---

lib/Plack/Handler/FCGI.pm
t/Plack-Handler/fcgi_cleanup.t

Having cleanup support in the FCGI Handler will be beneficial to us as it allows post-processing of tasks after the request has been served to the client and we would like to do our request logging at that point.

Add support for the psgix.cleanup extension

---

lib/HTTP/Server/PSGI.pm

Hi,
On Android with [Termux](https://termux.com/) and Perl 5.24.0:
```
u0_a168@localhost:~$ perl -MSocket=TCP_NODELAY -e TCP_NODELAY
Your vendor has not defined Socket macro TCP_NODELAY, used at -e line 1
```
Could you add some workaround, please?

Do not set if TCP_NODELAY is not available

---

lib/Plack/App/URLMap.pm

Currently `plackup -e 'sub { [200,[],["ok"]] }'` emits warnings under old perls
```
❯ perl -v
This is perl, v5.8.1 built for darwin-2level
...
❯ plackup -e 'sub {[200,[],["ok"]]}'
Useless use of a constant in void context at /Users/skaji/env/plenv/versions/5.8.1/lib/perl5/site_perl/5.8.1/Plack/App/URLMap.pm line 55.
Useless use of a constant in void context at /Users/skaji/env/plenv/versions/5.8.1/lib/perl5/site_perl/5.8.1/Plack/App/URLMap.pm line 61.
Useless use of a constant in void context at /Users/skaji/env/plenv/versions/5.8.1/lib/perl5/site_perl/5.8.1/Plack/App/URLMap.pm line 74.
HTTP::Server::PSGI: Accepting connections at http://0:5000/
```
I would be nice if Plack silences these warnings.

silence warnings under old perls

---

lib/Plack/Request.pm

Proposed patch for https://github.com/plack/Plack/issues/624

Plack::Request: Correct documentation of content_type and content_length

---

lib/Plack/Util.pm

The doc of `encode_html` had typo

Fix typo in doc of Plack::Util

---

t/Plack-Middleware/cgi-bin/hello.py
t/Plack-Middleware/cgibin_exec.t

Support for Python 2 will end on 2020-01-01. Given this, it make sense to move t/Plack-Middleware/cgi-bin/hello.py to use Python 3 instead.

Convert hello.py to Python 3

---

lib/Plack/Runner.pm

Filesys::Notify::Simple 0.13 with Linux::Inotify2 dies when passed nonexistent path.
This behavior was instroduced in https://github.com/miyagawa/Filesys-Notify-Simple/pull/21 .
`plackup` adds some paths to watch paths implicitly, that causes problems like below:
* `plackup -R /path/to/watch /path/to/app.psgi` dies when the `lib` directory does not exist in same directory of psgi file
* `plackup -R /path/to/watch -e 'sub { ... }'` dies when the `lib` directory does not exist in current directory

plackup: Check the default path of watch exists

---

lib/Plack/Middleware.pm

Whilst writing my own post processing middleware, I used the example in the pod as a base and kept getting the following error (running in strict mode):
```
Can't use an undefined value as a subroutine reference at lib/Plack/Middleware/PDF.pm line 8
```
My initial module code was:
```
package Plack::Middleware::PDF;
use Plack::Util;
use parent qw( Plack::Middleware );
sub call {
my($self, $env) = @_;
my $res = $app->($env);
return Plack::Util::response_cb($res, sub {
my $res = shift;
});
}
1;
```
Which is a copy of what's in these docs.
The problem comes from `my $res = $app->($env);` which should be `my $res = $self->app->($env);`. Which is how it is in all the other examples in this file other than the one I use.
Thanks

Fixed typo in middleware pod

---

lib/HTTP/Message/PSGI.pm
t/HTTP-Message-PSGI/empty_delayed_writer.t

If a delayed writer is used, but ->write is never called, the body
arrayref would never get created, leading to errors.

fix HTTP::Message::PSGI handling a delayed writer with no content

---

cpanfile
lib/Plack/Request.pm
t/Plack-Request/body-unbuffered.t

fixes #655 
Bump HTTP::Entity::Parser dependency to handle empty Content-Type as an octet-stream blob, and skip short-circuiting when Content-Type is empty inside Plack::Request as well.

fix a bug with Request body access when Content-Type is empty

---

lib/Plack/App/File.pm
t/Plack-Middleware/static.t

Static file requests (handled by Plack::App::File, which is used
by Plack::Middleware::Static) were allowing any request method,
including POST or DELETE.
This change only allows GET and HEAD requests. Other requests
will receive a HTTP 405 error.
Fixes #660.

Restrict Plack::App::File request methods, GH#660

---

lib/Plack/LWPish.pm

HTTP::Tiny doesn't verify TLS/SSL certificates by default. This PR sets that flag for the default user agent so HTTPS certificates are verified like LWP does.
Current (insecure) Plack::LWPish behaviour:
```
$ perl -Ilib -MPlack::LWPish -MHTTP::Request -E 'say Plack::LWPish->new->request(HTTP::Request->new("GET","https://self-signed.badssl.com"))->content'
<!DOCTYPE html>
[..]
```
Compared to LWP:
```
$ perl -MLWP::UserAgent -E 'say LWP::UserAgent->new->request(HTTP::Request->new("GET","https://self-signed.badssl.com"))->content'                                                                                                    
Can't connect to self-signed.badssl.com:443 (certificate verify failed)
```
With this fix applied, certificates are checked and the request fails:
```
$ perl -Ilib …
```

Set `verify_SSL=>1` by default for HTTP::Tiny in Plack::LWPish

---

.github/workflows/linux.yml
cpanfile

Some of the transient dependencies have the requirement for 5.10 and 5.12 and CI is currently failing. This PR just adds the runtime requirement of perl 5.12, without adding the explicit `use 5.012;` line so if someone wants to install and run it by hand it will work just fine.

Bump minimum perl requirement to 5.12

---

.github/workflows/linux.yml

This reverts commit 268b7f3ea3ed4225f3c40b11948d8cd0d27da8ee.
Currently, 5.38 is available.

Revert "perl:5.38 seems unavailable yet"

---

t/HTTP-Server-PSGI/listen.t

While hacking on Plack we noticed this timeout is instantiated but never used, thanks.

Add previously unused UA timeout to User Agent in HTTP::Server::PSGI test

---

.github/workflows/linux.yml

Perl 5.40 has been released. It is also available as a Docker image.
https://github.com/perl/docker-perl/blob/310b7bc1e03fa38094922c1a2e2cbd608bd0b3a4/5.040.000-main-bookworm/Dockerfile

Add perl:5.40

---

lib/HTTP/Message/PSGI.pm

This is a straightforward change to avoid using `try { $object->isa(...) }`. There are two other `isa` calls in code and they also use `blessed` and not `try`, so this makes the code base more consistent.

Avoid try block just for checking $object->isa
